%YAML 1.2
---
pipeline_version: "v0.1"
emails: " -c chouh@nih.gov"
FASTQ_prefix: "Sample_"
FASTQ_suffix_R1: "_R1.fastq.gz"
FASTQ_suffix_R2: "_R2.fastq.gz"
FASTQ_suffix_SE: "_R1.fastq.gz"
app_home: "/data/khanlab/apps"
version_common:
    fastqc: "0.11.9"
    samtools: "1.9"
    bedtools: "2.29.2"
    R: "3.4"
    python2: "2.7"
    python3: "3.6"
    picard: "2.22.2"
    snakemake: "5.13.0"
    sigularity: "3.6.4"
cluster_common:
    small: "--partition=quick,norm    --time=03:00:00 --mem=08G  --cpus-per-task=1   --gres=lscratch:05"
    subflow: "--partition=quick,norm    --time=2-00:00:00 --mem=08G  --cpus-per-task=1   --gres=lscratch:05"
    medium: "--partition=ccr,norm    --time=24:00:00 --mem=32G  --cpus-per-task=8  --gres=lscratch:05"
    large: "--partition=ccr,norm    --time=24:00:00 --mem=120G  --cpus-per-task=24  --gres=lscratch:05"
