%YAML 1.2
---
juicer_jar: "/usr/local/apps/juicer/juicer-1.5.6/scripts/juicer_tools.jar"
fithichip_instance: "FitHiChIP/FitHiChIP.sif"
peakachu:
    conda_path: "/data/khanlab/conda"
    env: "3dgenome"
    script: "/data/khanlab/apps/peakachu/scripts/peakachu"
    prob_cutoff: 0.7
    model: "ref/down30.h3k27ac.pkl"
cluster:
    hicpro: "--partition=ccr,norm --time=3-00:00:00 --mem=160G  --cpus-per-task=32  --gres=lscratch:200"
version:
    hicpro: "2.11.1"
    cutadapt: "2.10"
hg38:
    bowtie2_index: "ucsc.hg38"
    fragment_bed: "/data/khanlab/projects/HiC/reference_files/dpnii.ucsc.hg38.bed"
    capture_bed: "virtualHiC_MYOD1gene"
    juicer_genome: "/data/khanlab/projects/HiC/reference_files/chrom_hg38.sizes"
    chr_size: "/data/khanlab/projects/HiC/reference_files/chrom_hg38.sizes"
hg19:
    bowtie2_index: "ucsc.hg19"
    fragment_bed: "/data/khanlab/projects/HiC/reference_files/dpnii.ucsc.hg19.bed"
    capture_bed: "virtualHiC_MYOD1gene"
    juicer_genome: "hg19"
    chr_size: "/data/khanlab/projects/HiC/reference_files/chrom_hg19.sizes"
mm10:
    fragment_bed: "/data/khanlab/projects/HiC/reference_files/dpnii.ucsc.mm10.bed"
    bowtie2_index: mm10
    juicer_genome: mm10"
    chr_size: "/data/khanlab/projects/HiC/reference_files/chrom_mm10.sizes"

